feat: reskin of Profile MFE main page
openedx/frontend-app-profile pull request #1114
Opened 2024-10-24 14:07 UTC by eemaanamir

Ticket:[ INF-1570](https://2u-internal.atlassian.net/browse/INF-1570)

Backend PR: [Link](https://github.com/openedx/edx-platform/pull/35760)
edx-internal PR: [Link](https://github.com/edx/edx-internal/pull/11827)

Reskinning the Profile MFE main page according to the provided [Figma](https://www.figma.com/design/q6z6cpJsbBBcnPZLPS7KEu/Marketplace-Visual-Design?node-id=12984-25978&node-type=frame).

### Before: 
![58ff4399398be30e272fca6cbd82712d](https://github.com/user-attachments/assets/e2e00ee3-8517-4066-8db9-549479867ea0)

### After: 
![localhost_1995_u_edx](https://github.com/user-attachments/assets/da1194e6-3197-4847-904d-50b361127c4a)

2024-11-07 21:07 UTC, sundasnoreen12 requested changes

2024-11-07 21:07 UTC, sundasnoreen12 commented on src/profile-v2/ProfilePage.jsx
> +export default injectIntl(withParams(ProfilePage));
instead of injectInt import it from 
import { useIntl } from '@edx/frontend-platform/i18n';
and declare as   const intl = useIntl();

2024-11-07 21:07 UTC, sundasnoreen12 commented on src/profile-v2/ProfilePage.jsx
> +  }).isRequired,
no need for this

2024-11-13 11:39 UTC, awais-ansari approved these changes

2024-11-13 11:39 UTC, awais-ansari commented on src/profile-v2/ProfilePage.jsx
> +      <Hyperlink className="btn btn-brand btn-rounded font-weight-normal px-4 py-0625rem text-nowrap" target="_blank" showLaunchIcon={false} destination={viewMyRecordsUrl}>
line length 120 character

2024-11-13 11:39 UTC, awais-ansari commented on src/profile-v2/ProfilePage.jsx
> +      {renderContent()}
replace with HTML

2024-11-13 18:13 UTC, sundasnoreen12 approved these changes
PR LGTM

2024-11-18 08:36 UTC, merged