chore: update paragon and frontend-build in profile
openedx/frontend-app-profile pull request #975
Opened 2024-02-27 09:27 UTC by Yagnesh1998

There is an edx organization on NPM that currently publishes many packages. An organization can't be renamed but there is a process for moving packages between organizations. The edx organization or scope as NPM calls it, has both packages that are a part of the Open edX ecosystem as well as packages that are specific to edx.org. To reduce confusion we'll be moving the openedx packages to a new openedx scope in NPM.

2024-02-27 09:27 UTC, openedx-webhooks commented
Thanks for the pull request, @Yagnesh1998! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-02-28 16:07 UTC, arbrandes commented
@Yagnesh1998, mind resolving conflicts?  Thanks!

2024-03-06 17:49 UTC, jsnwesson commented
Just noting this for Aperture's review since this _might_ require a follow-up change in our stage/prod build config once this is merged.

2024-03-07 22:00 UTC, MaxFrank13 approved these changes

2024-03-08 13:45 UTC, arbrandes requested changes

2024-03-20 18:59 UTC, arbrandes requested changes
Trying to understand the decisions, here.

2024-03-20 18:59 UTC, arbrandes commented on package.json
> +    "@edx/frontend-component-footer": "13.0.2",
Why are we downgrading the footer?

2024-03-20 18:59 UTC, arbrandes commented on package.json
> +    "@edx/frontend-platform": "7.0.1",
Why downgrade frontend-platform?

2024-03-20 19:30 UTC, Yagnesh1998 commented on package.json
> +    "@edx/frontend-component-footer": "13.0.2",
there may be some misunderstanding

2024-03-29 12:22 UTC, justinhynes commented
@Yagnesh1998 Just another bump requesting conflict resolution. Would you be able to address any of the questions/comments on the PR too? TIA!

2024-04-11 15:49 UTC, deborahgu commented
@Yagnesh1998 is this PR still in process? Will you be able to resolve the conflicts?

@arbrandes  I am pretty sure that @Yagnesh1998  resolved your questions (by fixing the accidentally downgraded packages); am I correct?

2024-04-22 20:07 UTC, closed without merging

2024-04-22 20:07 UTC, openedx-webhooks commented
@Yagnesh1998 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-profile&entry.867055334=https://github.com/openedx/frontend-app-profile/pull/975&entry.1484655318=https://github.com/Yagnesh1998&entry.752974735=2024-02-27+09:27&entry.1917517419=2024-04-22+20:07&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->

2024-04-22 20:07 UTC, openedx-webhooks commented
@Yagnesh1998 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-profile&entry.867055334=https://github.com/openedx/frontend-app-profile/pull/975&entry.1484655318=https://github.com/Yagnesh1998&entry.752974735=2024-02-27+09:27&entry.1917517419=2024-04-22+20:07&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->